language: ruby
rvm:
  - 2.7.2
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - QMAKE=/usr/lib/x86_64-linux-gnu/qt4/bin/qmake
addons:
  apt:
    sources:
      - ubuntu-sdk-team
    packages:
      - libqt5webkit5-dev
      - qtdeclarative5-dev
  chrome: stable
bundler_args: --jobs=3 --retry=3 --without development
script: xvfb-run bundle exec rake
services:
  - postgresql
before_script:
  - psql -c 'create database cfp_app_test;' -U postgres
